name: FalchusChunks
version: ${project.version}
description: A blazingly fast chunk generator.
main: com.falchus.chunks.Main
author: Falchus
website: falchus.com/chunks

depend: [FalchusLib]

commands:
  generate:
    permission: falchus.generate
    aliases: [gen]

permissions:
  falchus.generate:
    default: op